import { apiClient } from './api'

const mockKlasifikasi = [
  { id: 1, kode: '000', deskripsi: 'UMUM', uraian: 'UMUM' },
  { id: 2, kode: '000.1', deskripsi: 'KETATAUSAHAAN DAN KERUMAHTANGGAAN', uraian: 'KETATAUSAHAAN DAN KERUMAHTANGGAAN' },
  { id: 3, kode: '000.1.1', deskripsi: 'Telekomunikasi', uraian: 'Telekomunikasi' },
  { id: 4, kode: '000.1.2', deskripsi: 'Perjalanan Dinas Dalam Negeri', uraian: 'Perjalanan Dinas Dalam Negeri' },
  { id: 5, kode: '000.1.2.1', deskripsi: 'Perjalanan Dinas Kepala Daerah', uraian: 'Perjalanan Dinas Kepala Daerah' },
  { id: 6, kode: '000.1.2.2', deskripsi: 'Perjalanan Dinas DPRD', uraian: 'Perjalanan Dinas DPRD' },
  { id: 7, kode: '000.1.2.3', deskripsi: 'Perjalanan Dinas Pegawai', uraian: 'Perjalanan Dinas Pegawai' },
  { id: 8, kode: '000.1.3', deskripsi: 'Perjalanan Dinas Luar Negeri', uraian: 'Perjalanan Dinas Luar Negeri' },
  { id: 9, kode: '000.1.3.1', deskripsi: 'Perjalanan Dinas Kepala Daerah', uraian: 'Perjalanan Dinas Kepala Daerah' },
  { id: 10, kode: '000.1.3.2', deskripsi: 'Perjalanan Dinas DPRD', uraian: 'Perjalanan Dinas DPRD' },
  { id: 11, kode: '000.1.3.3', deskripsi: 'Perjalanan Dinas Pegawai', uraian: 'Perjalanan Dinas Pegawai' },
  { id: 12, kode: '000.1.4', deskripsi: 'Penggunaan Fasilitas Kantor (Ruang/Gedung/Kendaraan/Wisma)', uraian: 'Penggunaan Fasilitas Kantor (Ruang/Gedung/Kendaraan/Wisma)' },
  { id: 13, kode: '000.1.5', deskripsi: 'Rapat Pimpinan (Notula/Risalah)', uraian: 'Rapat Pimpinan (Notula/Risalah)' },
  { id: 14, kode: '000.1.6', deskripsi: 'Penyediaan Konsumsi', uraian: 'Penyediaan Konsumsi' },
  { id: 15, kode: '000.1.7', deskripsi: 'Pengurusan Kendaraan Dinas', uraian: 'Pengurusan Kendaraan Dinas' },
  { id: 16, kode: '000.1.7.1', deskripsi: 'Pengurusan surat-surat kendaraan dinas', uraian: 'Pengurusan surat-surat kendaraan dinas' },
  { id: 17, kode: '000.1.7.2', deskripsi: 'Pemeliharaan dan perbaikan', uraian: 'Pemeliharaan dan perbaikan' },
  { id: 18, kode: '000.1.7.3', deskripsi: 'Pengurusan kehilangan dan masalah kendaraan', uraian: 'Pengurusan kehilangan dan masalah kendaraan' },
  { id: 19, kode: '000.1.8', deskripsi: 'Pemeliharaan Gedung Taman dan Peralatan Kantor', uraian: 'Pemeliharaan Gedung Taman dan Peralatan Kantor' },
  { id: 20, kode: '000.1.8.1', deskripsi: 'Pertamanan/ Landscape', uraian: 'Pertamanan/ Landscape' },
  { id: 21, kode: '000.1.8.2', deskripsi: 'Penghijauan', uraian: 'Penghijauan' },
  { id: 22, kode: '000.1.8.3', deskripsi: 'Perbaikan Gedung', uraian: 'Perbaikan Gedung' },
  { id: 23, kode: '000.1.8.4', deskripsi: 'Perbaikan Peralatan Kantor', uraian: 'Perbaikan Peralatan Kantor' },
  { id: 24, kode: '000.1.8.5', deskripsi: 'Perbaikan Rumah Dinas/ Wisma', uraian: 'Perbaikan Rumah Dinas/ Wisma' },
  { id: 25, kode: '000.1.8.6', deskripsi: 'Kebersihan Gedung dan Taman', uraian: 'Kebersihan Gedung dan Taman' },
  { id: 26, kode: '000.1.9', deskripsi: 'Pengelolaan Jaringan Listrik Air Telepon dan Komputer', uraian: 'Pengelolaan Jaringan Listrik Air Telepon dan Komputer' },
  { id: 27, kode: '000.1.9.1', deskripsi: 'Perbaikan / Pemeliharaan', uraian: 'Perbaikan / Pemeliharaan' },
  { id: 28, kode: '000.1.9.2', deskripsi: 'Pemasangan', uraian: 'Pemasangan' },
  { id: 29, kode: '000.1.10', deskripsi: 'Ketertiban dan Keamanan', uraian: 'Ketertiban dan Keamanan' },
  { id: 30, kode: '000.1.10.1', deskripsi: 'Pengamanan Penjagaan dan Pengawalan Pejabat/Kantor/Rumah Dinas', uraian: 'Pengamanan Penjagaan dan Pengawalan Pejabat/Kantor/Rumah Dinas' },
  { id: 31, kode: '000.1.10.2', deskripsi: 'Laporan Ketertiban dan Keamanan', uraian: 'Laporan Ketertiban dan Keamanan' },
  { id: 32, kode: '000.1.11', deskripsi: 'Administrasi Pengelolaan Parkir', uraian: 'Administrasi Pengelolaan Parkir' },
  { id: 33, kode: '000.1.12', deskripsi: 'Administrasi Pakaian Dinas (Pegawai/Satpam/Kebersihan)', uraian: 'Administrasi Pakaian Dinas (Pegawai/Satpam/Kebersihan)' },
  { id: 34, kode: '000.2', deskripsi: 'PERLENGKAPAN', uraian: 'PERLENGKAPAN' },
  { id: 35, kode: '000.2.1', deskripsi: 'Inventarisasi dan Penyimpanan', uraian: 'Inventarisasi dan Penyimpanan' },
  { id: 36, kode: '000.2.1.1', deskripsi: 'Data hasil inventarisasi dan penyimpanan', uraian: 'Data hasil inventarisasi dan penyimpanan' },
  { id: 37, kode: '000.2.2.2', deskripsi: 'Laporan dan evaluasi inventarisasi dan penyimpanan', uraian: 'Laporan dan evaluasi inventarisasi dan penyimpanan' },
  { id: 38, kode: '000.2.2', deskripsi: 'Pemeliharaan peralatan kantor', uraian: 'Pemeliharaan peralatan kantor' },
  { id: 39, kode: '000.2.2.1', deskripsi: 'Data hasil pemeliharaan kantor', uraian: 'Data hasil pemeliharaan kantor' },
  { id: 40, kode: '000.2.2.2', deskripsi: 'Laporan dan evaluasi pemeliharaan kantor', uraian: 'Laporan dan evaluasi pemeliharaan kantor' },
  { id: 41, kode: '000.2.3', deskripsi: 'Distribusi', uraian: 'Distribusi' },
  { id: 42, kode: '000.2.3.1', deskripsi: 'Barang habis pakai', uraian: 'Barang habis pakai' },
  { id: 43, kode: '000.2.3.2', deskripsi: 'Barang milik daerah', uraian: 'Barang milik daerah' },
  { id: 44, kode: '000.2.4', deskripsi: 'Penghapusan Barang Milik Daerah (SK Tim/Berita Acara/Lelang)', uraian: 'Penghapusan Barang Milik Daerah (SK Tim/Berita Acara/Lelang)' },
  { id: 45, kode: '000.2.5', deskripsi: 'Pengelolaan Database Barang Milik Daerah', uraian: 'Pengelolaan Database Barang Milik Daerah' },
  { id: 46, kode: '000.3', deskripsi: 'PENGADAAN', uraian: 'PENGADAAN' },
  { id: 47, kode: '000.3.1', deskripsi: 'Rencana pengadaan Barang dan jasa (Identifikasi/Penyusunan RKP/KAK/RUP)', uraian: 'Rencana pengadaan Barang dan jasa (Identifikasi/Penyusunan RKP/KAK/RUP)' },
  { id: 48, kode: '000.3.2', deskripsi: 'Pengadaan Langsung (Pemilihan/Kontrak/Pelaksanaan)', uraian: 'Pengadaan Langsung (Pemilihan/Kontrak/Pelaksanaan)' },
  { id: 49, kode: '000.3.3', deskripsi: 'Pengadaan Tidak Langsung/Lelang', uraian: 'Pengadaan Tidak Langsung/Lelang' },
  { id: 50, kode: '000.3.4', deskripsi: 'Swakelola (Perencanaan/Pelaksanaan/Evaluasi)', uraian: 'Swakelola (Perencanaan/Pelaksanaan/Evaluasi)' },
  { id: 51, kode: '000.3.5', deskripsi: 'Pengolahan Sistem Informasi Pengadaan (Database/Kontrak)', uraian: 'Pengolahan Sistem Informasi Pengadaan (Database/Kontrak)' },
  { id: 52, kode: '000.3.6', deskripsi: 'Monitoring dan evaluasi pelaksanaan pengadaan', uraian: 'Monitoring dan evaluasi pelaksanaan pengadaan' },
  { id: 53, kode: '000.4', deskripsi: 'PERPUSTAKAAN', uraian: 'PERPUSTAKAAN' },
  { id: 54, kode: '000.4.1', deskripsi: 'Kebijakan di bidang Perpustakaan', uraian: 'Kebijakan di bidang Perpustakaan' },
  { id: 55, kode: '000.4.2', deskripsi: 'Deposit Bahan Pustaka', uraian: 'Deposit Bahan Pustaka' },
  { id: 56, kode: '000.4.2.1', deskripsi: 'Serah Simpan Karya Cetak dan Karya Rekam', uraian: 'Serah Simpan Karya Cetak dan Karya Rekam' },
  { id: 57, kode: '000.4.2.2', deskripsi: 'Pangkalan Data Penerbit dan Pengusaha Rekaman', uraian: 'Pangkalan Data Penerbit dan Pengusaha Rekaman' },
  { id: 58, kode: '000.4.2.3', deskripsi: 'Terbitan Internasional dan Regional', uraian: 'Terbitan Internasional dan Regional' },
  { id: 59, kode: '000.4.2.4', deskripsi: 'Pemantauan Wajib Serah Simpan', uraian: 'Pemantauan Wajib Serah Simpan' },
  { id: 60, kode: '000.4.2.5', deskripsi: 'Bibliografi dan Katalog', uraian: 'Bibliografi dan Katalog' },
  { id: 61, kode: '000.4.3', deskripsi: 'Koleksi Pustaka (Pembelian/Hibah/Hadiah/Tukar Menukar)', uraian: 'Koleksi Pustaka (Pembelian/Hibah/Hadiah/Tukar Menukar)' },
  { id: 62, kode: '000.4.4', deskripsi: 'Pengolahan Bahan Pustaka', uraian: 'Pengolahan Bahan Pustaka' },
  { id: 63, kode: '000.4.5', deskripsi: 'Pangkalan Data Katalog Koleksi', uraian: 'Pangkalan Data Katalog Koleksi' },
  { id: 64, kode: '000.4.6', deskripsi: 'Layanan Perpustakaan (Keanggotaan/Peminjaman/Gemar Baca)', uraian: 'Layanan Perpustakaan (Keanggotaan/Peminjaman/Gemar Baca)' },
  { id: 65, kode: '000.4.7', deskripsi: 'Kerjasama Perpustakaan (MoU/Perjanjian)', uraian: 'Kerjasama Perpustakaan (MoU/Perjanjian)' },
  { id: 66, kode: '000.4.8', deskripsi: 'Pengembangan Implementasi Teknologi Informasi Perpustakaan', uraian: 'Pengembangan Implementasi Teknologi Informasi Perpustakaan' },
  { id: 67, kode: '000.4.10', deskripsi: 'Konservasi (Perawatan/Perbaikan/Penjilidan)', uraian: 'Konservasi (Perawatan/Perbaikan/Penjilidan)' },
  { id: 68, kode: '000.5', deskripsi: 'KEARSIPAN', uraian: 'KEARSIPAN' },
  { id: 69, kode: '000.5.1', deskripsi: 'Kebijakan di bidang kearsipan oleh Pemerintah Daerah', uraian: 'Kebijakan di bidang kearsipan oleh Pemerintah Daerah' },
  { id: 70, kode: '000.5.2', deskripsi: 'Pembinaan Kearsipan', uraian: 'Pembinaan Kearsipan' },
  { id: 71, kode: '000.5.2.1', deskripsi: 'Pengembangan Profesi Arsiparis (Formasi/Analisis Kebutuhan)', uraian: 'Pengembangan Profesi Arsiparis (Formasi/Analisis Kebutuhan)' },
  { id: 72, kode: '000.5.2.2', deskripsi: 'Bimbingan Konsultasi Arsiparis', uraian: 'Bimbingan Konsultasi Arsiparis' },
  { id: 73, kode: '000.5.2.3', deskripsi: 'Penilaian Arsiparis', uraian: 'Penilaian Arsiparis' },
  { id: 74, kode: '000.5.2.4', deskripsi: 'Pemilihan Arsiparis Teladan', uraian: 'Pemilihan Arsiparis Teladan' },
  { id: 75, kode: '000.5.2.5', deskripsi: 'Data Base Arsiparis', uraian: 'Data Base Arsiparis' },
  { id: 76, kode: '000.5.2.7', deskripsi: 'Supervisi dan Evaluasi Kearsipan', uraian: 'Supervisi dan Evaluasi Kearsipan' },
  { id: 77, kode: '000.5.3', deskripsi: 'Pengelolaan Arsip Dinamis', uraian: 'Pengelolaan Arsip Dinamis' },
  { id: 78, kode: '000.5.3.1', deskripsi: 'Penciptaan (Registrasi/Buku Agenda/Kartu Kendali)', uraian: 'Penciptaan (Registrasi/Buku Agenda/Kartu Kendali)' },
  { id: 79, kode: '000.5.3.2', deskripsi: 'Pemberkasan Arsip Aktif', uraian: 'Pemberkasan Arsip Aktif' },
  { id: 80, kode: '000.5.3.3', deskripsi: 'Penataan Arsip Inaktif', uraian: 'Penataan Arsip Inaktif' },
  { id: 81, kode: '000.5.3.4', deskripsi: 'Penggunaan dan Bukti Peminjaman Arsip', uraian: 'Penggunaan dan Bukti Peminjaman Arsip' },
  { id: 82, kode: '000.5.3.5', deskripsi: 'Autentikasi Arsip Dinamis', uraian: 'Autentikasi Arsip Dinamis' },
  { id: 83, kode: '000.5.4', deskripsi: 'Program Arsip Vital (Identifikasi/Perlindungan/Penyelamatan)', uraian: 'Program Arsip Vital (Identifikasi/Perlindungan/Penyelamatan)' },
  { id: 84, kode: '000.5.5', deskripsi: 'Pengelolaan Arsip Terjaga', uraian: 'Pengelolaan Arsip Terjaga' },
  { id: 85, kode: '000.5.6', deskripsi: 'Penyusutan Arsip', uraian: 'Penyusutan Arsip' },
  { id: 86, kode: '000.5.6.1', deskripsi: 'Pemindahan Arsip', uraian: 'Pemindahan Arsip' },
  { id: 87, kode: '000.5.6.2', deskripsi: 'Pemusnahan Arsip (SK Panitia/Persetujuan ANRI/Berita Acara)', uraian: 'Pemusnahan Arsip (SK Panitia/Persetujuan ANRI/Berita Acara)' },
  { id: 88, kode: '000.5.6.3', deskripsi: 'Penyerahan Arsip Statis', uraian: 'Penyerahan Arsip Statis' },
  { id: 89, kode: '000.5.7', deskripsi: 'Alih Media Arsip (Digitalisasi)', uraian: 'Alih Media Arsip (Digitalisasi)' },
  { id: 90, kode: '000.5.9', deskripsi: 'Pengelolaan Arsip Statis', uraian: 'Pengelolaan Arsip Statis' },
  { id: 91, kode: '000.5.9.1', deskripsi: 'Akuisisi Arsip Statis', uraian: 'Akuisisi Arsip Statis' },
  { id: 92, kode: '000.5.9.3', deskripsi: 'Sejarah Lisan (Wawancara/Hasil Rekaman)', uraian: 'Sejarah Lisan (Wawancara/Hasil Rekaman)' },
  { id: 93, kode: '000.5.9.5', deskripsi: 'Penyusunan Sarana Bantu Temu Balik (Inventory/Guide)', uraian: 'Penyusunan Sarana Bantu Temu Balik (Inventory/Guide)' },
  { id: 94, kode: '000.5.9.6', deskripsi: 'Preservasi Preventif (Penyimpanan/Hama)', uraian: 'Preservasi Preventif (Penyimpanan/Hama)' },
  { id: 95, kode: '000.5.15', deskripsi: 'Pengawasan Kearsipan (Internal/Eksternal)', uraian: 'Pengawasan Kearsipan (Internal/Eksternal)' },
  { id: 96, kode: '000.6', deskripsi: 'PERSANDIAN', uraian: 'PERSANDIAN' },
  { id: 97, kode: '000.6.1', deskripsi: 'Kebijakan di bidang Persandian', uraian: 'Kebijakan di bidang Persandian' },
  { id: 98, kode: '000.6.2', deskripsi: 'Pengamanan Persandian (Sinyal/Kripto/Materiil)', uraian: 'Pengamanan Persandian (Sinyal/Kripto/Materiil)' },
  { id: 99, kode: '000.6.3', deskripsi: 'Pengkajian Persandian (Kriptografi/Komunikasi Sandi)', uraian: 'Pengkajian Persandian (Kriptografi/Komunikasi Sandi)' },
  { id: 100, kode: '000.6.5', deskripsi: 'Layanan Sertifikasi Elektronik', uraian: 'Layanan Sertifikasi Elektronik' },
  { id: 101, kode: '000.7', deskripsi: 'PERENCANAAN PEMBANGUNAN', uraian: 'PERENCANAAN PEMBANGUNAN' },
  { id: 102, kode: '000.7.1', deskripsi: 'Musrenbang (Provinsi/Nasional/Kota/Kecamatan/Desa)', uraian: 'Musrenbang (Provinsi/Nasional/Kota/Kecamatan/Desa)' },
  { id: 103, kode: '000.7.2', deskripsi: 'Perencanaan Pembangunan Daerah', uraian: 'Perencanaan Pembangunan Daerah' },
  { id: 104, kode: '000.7.2.1', deskripsi: 'Rencana Pembangunan Jangka Panjang (RPJP)', uraian: 'Rencana Pembangunan Jangka Panjang (RPJP)' },
  { id: 105, kode: '000.7.2.2', deskripsi: 'Rencana Pembangunan Jangka Menengah (RPJM)', uraian: 'Rencana Pembangunan Jangka Menengah (RPJM)' },
  { id: 106, kode: '000.7.2.4', deskripsi: 'Rencana Pembangunan Tahunan (RKP)', uraian: 'Rencana Pembangunan Tahunan (RKP)' },
  { id: 107, kode: '000.7.2.7', deskripsi: 'Penetapan / Kontrak Kinerja', uraian: 'Penetapan / Kontrak Kinerja' },
  { id: 108, kode: '000.8', deskripsi: 'ORGANISASI DAN TATA LAKSANA', uraian: 'ORGANISASI DAN TATA LAKSANA' },
  { id: 109, kode: '000.8.1', deskripsi: 'Struktur Organisasi (Pembentukan/Pengubahan/Pembubaran)', uraian: 'Struktur Organisasi (Pembentukan/Pengubahan/Pembubaran)' },
  { id: 110, kode: '000.8.2', deskripsi: 'Uraian Jabatan (Analisa Jabatan/Beban Kerja)', uraian: 'Uraian Jabatan (Analisa Jabatan/Beban Kerja)' },
  { id: 111, kode: '000.8.3', deskripsi: 'Ketatalaksanaan (Proses Bisnis/SOP/Pelayanan Publik)', uraian: 'Ketatalaksanaan (Proses Bisnis/SOP/Pelayanan Publik)' },
  { id: 112, kode: '000.8.6', deskripsi: 'Koordinasi Penguatan Reformasi dan Birokrasi', uraian: 'Koordinasi Penguatan Reformasi dan Birokrasi' },
  { id: 113, kode: '000.9', deskripsi: 'PENELITIAN PENGKAJIAN DAN PENGEMBANGAN', uraian: 'PENELITIAN PENGKAJIAN DAN PENGEMBANGAN' },
  { id: 114, kode: '100', deskripsi: 'PEMERINTAHAN', uraian: 'PEMERINTAHAN' },
  { id: 115, kode: '100.1', deskripsi: 'OTONOMI DAERAH', uraian: 'OTONOMI DAERAH' },
  { id: 116, kode: '100.1.2', deskripsi: 'Penyelenggaraan Pemerintah Daerah (Fasilitasi/Monitoring)', uraian: 'Penyelenggaraan Pemerintah Daerah (Fasilitasi/Monitoring)' },
  { id: 117, kode: '100.1.3', deskripsi: 'Penataan Daerah (Pemekaran/Otsus)', uraian: 'Penataan Daerah (Pemekaran/Otsus)' },
  { id: 118, kode: '100.1.4', deskripsi: 'Pemilihan Kepala Daerah dan DPRD', uraian: 'Pemilihan Kepala Daerah dan DPRD' },
  { id: 119, kode: '100.2', deskripsi: 'PEMERINTAHAN UMUM', uraian: 'PEMERINTAHAN UMUM' },
  { id: 120, kode: '100.2.1', deskripsi: 'Kebijakan bidang Pemerintahan Umum', uraian: 'Kebijakan bidang Pemerintahan Umum' },
  { id: 121, kode: '100.2.2', deskripsi: 'Dekonsentrasi dan Kerjasama', uraian: 'Dekonsentrasi dan Kerjasama' },
  { id: 122, kode: '100.2.3', deskripsi: 'Wilayah Administrasi dan Perbatasan (Toponimi/Batas Daerah)', uraian: 'Wilayah Administrasi dan Perbatasan (Toponimi/Batas Daerah)' },
  { id: 123, kode: '100.3', deskripsi: 'HUKUM', uraian: 'HUKUM' },
  { id: 124, kode: '100.3.1', deskripsi: 'Program Legislasi', uraian: 'Program Legislasi' },
  { id: 125, kode: '100.3.2', deskripsi: 'Rancangan Peraturan Perundang-Undangan (Perda/Naskah Akademik)', uraian: 'Rancangan Peraturan Perundang-Undangan (Perda/Naskah Akademik)' },
  { id: 126, kode: '100.3.3', deskripsi: 'Keputusan/Ketetapan Pimpinan (Gubernur/Bupati/Walikota/Sekda)', uraian: 'Keputusan/Ketetapan Pimpinan (Gubernur/Bupati/Walikota/Sekda)' },
  { id: 127, kode: '100.3.4', deskripsi: 'Instruksi / Surat Edaran', uraian: 'Instruksi / Surat Edaran' },
  { id: 128, kode: '100.3.5', deskripsi: 'Surat Perintah', uraian: 'Surat Perintah' },
  { id: 129, kode: '100.3.7', deskripsi: 'Nota Kesepakatan (MOU) / Kontrak / Perjanjian', uraian: 'Nota Kesepakatan (MOU) / Kontrak / Perjanjian' },
  { id: 130, kode: '100.3.11', deskripsi: 'Kasus/ Sengketa Hukum (Pidana/Perdata/Arbitrase)', uraian: 'Kasus/ Sengketa Hukum (Pidana/Perdata/Arbitrase)' },
  { id: 131, kode: '100.3.13', deskripsi: 'Hak atas Kekayaan Intelektual (HAKI)', uraian: 'Hak atas Kekayaan Intelektual (HAKI)' },
  { id: 132, kode: '200', deskripsi: 'POLITIK', uraian: 'POLITIK' },
  { id: 133, kode: '200.1', deskripsi: 'KESATUAN BANGSA DAN POLITIK', uraian: 'KESATUAN BANGSA DAN POLITIK' },
  { id: 134, kode: '200.1.2', deskripsi: 'Bina Ideologi dan Wawasan Kebangsaan (Bela Negara)', uraian: 'Bina Ideologi dan Wawasan Kebangsaan (Bela Negara)' },
  { id: 135, kode: '200.1.3', deskripsi: 'Kewaspadaan Nasional (Intelijen/Konflik Sosial)', uraian: 'Kewaspadaan Nasional (Intelijen/Konflik Sosial)' },
  { id: 136, kode: '200.1.4', deskripsi: 'Ketahanan Seni Budaya Adat Agama dan Kemasyarakatan (Ormas)', uraian: 'Ketahanan Seni Budaya Adat Agama dan Kemasyarakatan (Ormas)' },
  { id: 137, kode: '200.1.5', deskripsi: 'Politik Dalam Negeri (Parpol/Pemilu)', uraian: 'Politik Dalam Negeri (Parpol/Pemilu)' },
  { id: 138, kode: '200.2', deskripsi: 'PEMILU', uraian: 'PEMILU' },
  { id: 139, kode: '200.2.2', deskripsi: 'Pemutakhiran Daftar Pemilih (DP4/DPS/DPT)', uraian: 'Pemutakhiran Daftar Pemilih (DP4/DPS/DPT)' },
  { id: 140, kode: '200.2.3', deskripsi: 'Pendaftaran dan Verifikasi Peserta Pemilu', uraian: 'Pendaftaran dan Verifikasi Peserta Pemilu' },
  { id: 141, kode: '200.2.8', deskripsi: 'Pemungutan dan Penghitungan Suara', uraian: 'Pemungutan dan Penghitungan Suara' },
  { id: 142, kode: '300', deskripsi: 'KEAMANAN DAN KETERTIBAN', uraian: 'KEAMANAN DAN KETERTIBAN' },
  { id: 143, kode: '300.1', deskripsi: 'SATUAN POLISI PAMONG PRAJA (Satpol PP)', uraian: 'SATUAN POLISI PAMONG PRAJA (Satpol PP)' },
  { id: 144, kode: '300.1.2', deskripsi: 'Tata Operasional dan Sarana Prasarana Satpol PP', uraian: 'Tata Operasional dan Sarana Prasarana Satpol PP' },
  { id: 145, kode: '300.2', deskripsi: 'PENANGGULANGAN BENCANA PENCARIAN DAN PERTOLONGAN', uraian: 'PENANGGULANGAN BENCANA PENCARIAN DAN PERTOLONGAN' },
  { id: 146, kode: '300.2.2', deskripsi: 'Perencanaan Penanggulangan Bencana (SAR/Logistik)', uraian: 'Perencanaan Penanggulangan Bencana (SAR/Logistik)' },
  { id: 147, kode: '300.2.8', deskripsi: 'Operasi Komunikasi (Berita SAR/Beacon)', uraian: 'Operasi Komunikasi (Berita SAR/Beacon)' },
  { id: 148, kode: '400', deskripsi: 'KESEJAHTERAAN RAKYAT', uraian: 'KESEJAHTERAAN RAKYAT' },
  { id: 149, kode: '400.1', deskripsi: 'PEMBANGUNAN DAERAH TERTINGGAL', uraian: 'PEMBANGUNAN DAERAH TERTINGGAL' },
  { id: 150, kode: '400.2', deskripsi: 'PEMBERDAYAAN PEREMPUAN DAN PERLINDUNGAN ANAK', uraian: 'PEMBERDAYAAN PEREMPUAN DAN PERLINDUNGAN ANAK' },
  { id: 151, kode: '400.2.3', deskripsi: 'Perlindungan Perempuan (Kekerasan/Trafficking)', uraian: 'Perlindungan Perempuan (Kekerasan/Trafficking)' },
  { id: 152, kode: '400.2.4', deskripsi: 'Perlindungan Anak (Hak Sipil/Anak Berhadapan Hukum)', uraian: 'Perlindungan Anak (Hak Sipil/Anak Berhadapan Hukum)' },
  { id: 153, kode: '400.2.5', deskripsi: 'Tumbuh Kembang Anak (Kota Layak Anak)', uraian: 'Tumbuh Kembang Anak (Kota Layak Anak)' },
  { id: 154, kode: '400.3', deskripsi: 'PENDIDIKAN', uraian: 'PENDIDIKAN' },
  { id: 155, kode: '400.3.2', deskripsi: 'PAUD (Bahan Ajar/Alat Permainan Edukatif)', uraian: 'PAUD (Bahan Ajar/Alat Permainan Edukatif)' },
  { id: 156, kode: '400.3.5', deskripsi: 'Pendidikan Dasar dan Menengah Pertama (Kurikulum/BOS/Bantuan Siswa)', uraian: 'Pendidikan Dasar dan Menengah Pertama (Kurikulum/BOS/Bantuan Siswa)' },
  { id: 157, kode: '400.3.7', deskripsi: 'Pembinaan Pendidik dan Tenaga Pendidik (Sertifikasi Guru/UKG)', uraian: 'Pembinaan Pendidik dan Tenaga Pendidik (Sertifikasi Guru/UKG)' },
  { id: 158, kode: '400.3.8', deskripsi: 'Sekolah Menengah Atas', uraian: 'Sekolah Menengah Atas' },
  { id: 159, kode: '400.3.10', deskripsi: 'Pendidik dan Tenaga Pendidik (SKP/Penilaian Prestasi)', uraian: 'Pendidik dan Tenaga Pendidik (SKP/Penilaian Prestasi)' },
  { id: 160, kode: '400.3.12', deskripsi: 'Data dan Statistik Pendidikan', uraian: 'Data dan Statistik Pendidikan' },
  { id: 161, kode: '400.4', deskripsi: 'KEOLAHRAGAAN', uraian: 'KEOLAHRAGAAN' },
  { id: 162, kode: '400.4.2', deskripsi: 'Olahraga Pendidikan', uraian: 'Olahraga Pendidikan' },
  { id: 163, kode: '400.4.3', deskripsi: 'Olahraga Rekreasi (Massal/Tradisional)', uraian: 'Olahraga Rekreasi (Massal/Tradisional)' },
  { id: 164, kode: '400.5', deskripsi: 'KEPEMUDAAN', uraian: 'KEPEMUDAAN' },
  { id: 165, kode: '400.5.2', deskripsi: 'Peningkatan Tenaga dan Sumber Daya Pemuda (Duta Pemuda)', uraian: 'Peningkatan Tenaga dan Sumber Daya Pemuda (Duta Pemuda)' },
  { id: 166, kode: '400.5.6', deskripsi: 'Kepemimpinan dan Kepeloporan Pemuda', uraian: 'Kepemimpinan dan Kepeloporan Pemuda' },
  { id: 167, kode: '400.6', deskripsi: 'KEBUDAYAAN', uraian: 'KEBUDAYAAN' },
  { id: 168, kode: '400.6.2', deskripsi: 'Pelestarian Cagar Budaya dan Permuseuman', uraian: 'Pelestarian Cagar Budaya dan Permuseuman' },
  { id: 169, kode: '400.6.3', deskripsi: 'Pembinaan Kesenian dan Perfilman', uraian: 'Pembinaan Kesenian dan Perfilman' },
  { id: 170, kode: '400.7', deskripsi: 'KESEHATAN', uraian: 'KESEHATAN' },
  { id: 171, kode: '400.7.2', deskripsi: 'Upaya Kesehatan Dasar (Puskesmas/Kedokteran Keluarga)', uraian: 'Upaya Kesehatan Dasar (Puskesmas/Kedokteran Keluarga)' },
  { id: 172, kode: '400.7.3', deskripsi: 'Upaya Kesehatan Rujukan (Rumah Sakit/KUK)', uraian: 'Upaya Kesehatan Rujukan (Rumah Sakit/KUK)' },
  { id: 173, kode: '400.7.8', deskripsi: 'Pengendalian Penyakit Menular (TB/AIDS/ISPA)', uraian: 'Pengendalian Penyakit Menular (TB/AIDS/ISPA)' },
  { id: 174, kode: '400.7.10', deskripsi: 'Pengendalian Penyakit Tidak Menular (Jantung/Diabetes/Kanker)', uraian: 'Pengendalian Penyakit Tidak Menular (Jantung/Diabetes/Kanker)' },
  { id: 175, kode: '400.7.13', deskripsi: 'Gizi (Kewaspadaan Gizi/Stunting)', uraian: 'Gizi (Kewaspadaan Gizi/Stunting)' },
  { id: 176, kode: '400.7.20', deskripsi: 'Kefarmasian (Apotek/Obat Rasional)', uraian: 'Kefarmasian (Apotek/Obat Rasional)' },
  { id: 177, kode: '400.9', deskripsi: 'SOSIAL', uraian: 'SOSIAL' },
  { id: 178, kode: '400.9.2', deskripsi: 'Kesejahteraan Sosial Anak', uraian: 'Kesejahteraan Sosial Anak' },
  { id: 179, kode: '400.9.4', deskripsi: 'Rehabilitasi Sosial (Disabilitas/Tuna Sosial)', uraian: 'Rehabilitasi Sosial (Disabilitas/Tuna Sosial)' },
  { id: 180, kode: '400.12', deskripsi: 'KEPENDUDUKAN DAN CATATAN SIPIL', uraian: 'KEPENDUDUKAN DAN CATATAN SIPIL' },
  { id: 181, kode: '400.12.3', deskripsi: 'Pencatatan Sipil (Kelahiran/Kematian/Nikah/Cerai)', uraian: 'Pencatatan Sipil (Kelahiran/Kematian/Nikah/Cerai)' },
  { id: 182, kode: '400.12.4', deskripsi: 'Sistem Informasi Administrasi Kependudukan (SIAK)', uraian: 'Sistem Informasi Administrasi Kependudukan (SIAK)' },
  { id: 183, kode: '400.13', deskripsi: 'KELUARGA BERENCANA', uraian: 'KELUARGA BERENCANA' },
  { id: 184, kode: '400.13.16', deskripsi: 'Kualitas Pelayanan KB Pemerintah', uraian: 'Kualitas Pelayanan KB Pemerintah' },
  { id: 185, kode: '400.13.26', deskripsi: 'Bina Keluarga Balita dan Anak', uraian: 'Bina Keluarga Balita dan Anak' },
  { id: 186, kode: '500', deskripsi: 'PEREKONOMIAN', uraian: 'PEREKONOMIAN' },
  { id: 187, kode: '500.1', deskripsi: 'KETAHANAN PANGAN', uraian: 'KETAHANAN PANGAN' },
  { id: 188, kode: '500.1.2', deskripsi: 'Ketersediaan dan Kerawanan Pangan', uraian: 'Ketersediaan dan Kerawanan Pangan' },
  { id: 189, kode: '500.2', deskripsi: 'PERDAGANGAN', uraian: 'PERDAGANGAN' },
  { id: 190, kode: '500.2.2', deskripsi: 'Perdagangan Dalam Negeri (Pasar/UMKM)', uraian: 'Perdagangan Dalam Negeri (Pasar/UMKM)' },
  { id: 191, kode: '500.3', deskripsi: 'KOPERASI DAN USAHA KECIL MENENGAH', uraian: 'KOPERASI DAN USAHA KECIL MENENGAH' },
  { id: 192, kode: '500.3.4', deskripsi: 'Pembiayaan (Simpan Pinjam/Kredit)', uraian: 'Pembiayaan (Simpan Pinjam/Kredit)' },
  { id: 193, kode: '500.4', deskripsi: 'KEHUTANAN', uraian: 'KEHUTANAN' },
  { id: 194, kode: '500.4.3', deskripsi: 'Planologi Kehutanan (Tata Ruang Hutan)', uraian: 'Planologi Kehutanan (Tata Ruang Hutan)' },
  { id: 195, kode: '500.4.6', deskripsi: 'Perlindungan Hutan dan Konservasi Alam', uraian: 'Perlindungan Hutan dan Konservasi Alam' },
  { id: 196, kode: '500.5', deskripsi: 'KELAUTAN DAN PERIKANAN', uraian: 'KELAUTAN DAN PERIKANAN' },
  { id: 197, kode: '500.5.2', deskripsi: 'Perikanan Tangkap (Kapal/Alat Tangkap)', uraian: 'Perikanan Tangkap (Kapal/Alat Tangkap)' },
  { id: 198, kode: '500.5.3', deskripsi: 'Perikanan Budidaya (Benih/Hama Penyakit)', uraian: 'Perikanan Budidaya (Benih/Hama Penyakit)' },
  { id: 199, kode: '500.6', deskripsi: 'PERTANIAN', uraian: 'PERTANIAN' },
  { id: 200, kode: '500.6.2', deskripsi: 'Perlindungan Hortikultura', uraian: 'Perlindungan Hortikultura' },
  { id: 201, kode: '500.6.10', deskripsi: 'Budidaya Serealia (Padi/Jagung)', uraian: 'Budidaya Serealia (Padi/Jagung)' },
  { id: 202, kode: '500.9', deskripsi: 'PERINDUSTRIAN', uraian: 'PERINDUSTRIAN' },
  { id: 203, kode: '500.10', deskripsi: 'ENERGI DAN SUMBER DAYA MINERAL', uraian: 'ENERGI DAN SUMBER DAYA MINERAL' },
  { id: 204, kode: '500.10.7', deskripsi: 'Hulu Minyak dan Gas Bumi (Eksplorasi/Eksploitasi)', uraian: 'Hulu Minyak dan Gas Bumi (Eksplorasi/Eksploitasi)' },
  { id: 205, kode: '500.10.12', deskripsi: 'Panas Bumi', uraian: 'Panas Bumi' },
  { id: 206, kode: '500.11', deskripsi: 'PERHUBUNGAN', uraian: 'PERHUBUNGAN' },
  { id: 207, kode: '500.11.2', deskripsi: 'Jaringan Prasarana (Terminal Tipe A/B/C)', uraian: 'Jaringan Prasarana (Terminal Tipe A/B/C)' },
  { id: 208, kode: '500.11.8', deskripsi: 'Angkutan Penumpang (Tarif/Izin Trayek)', uraian: 'Angkutan Penumpang (Tarif/Izin Trayek)' },
  { id: 209, kode: '500.12', deskripsi: 'KOMUNIKASI DAN INFORMATIKA', uraian: 'KOMUNIKASI DAN INFORMATIKA' },
  { id: 210, kode: '500.12.6', deskripsi: 'e-Government (Tata Kelola/Aplikasi)', uraian: 'e-Government (Tata Kelola/Aplikasi)' },
  { id: 211, kode: '600', deskripsi: 'PEKERJAAN UMUM DAN KETENAGAAN', uraian: 'PEKERJAAN UMUM DAN KETENAGAAN' },
  { id: 212, kode: '600.1', deskripsi: 'PEKERJAAN UMUM', uraian: 'PEKERJAAN UMUM' },
  { id: 213, kode: '600.1.2', deskripsi: 'Penatagunaan Sumber Daya Air', uraian: 'Penatagunaan Sumber Daya Air' },
  { id: 214, kode: '600.1.7', deskripsi: 'Pengembangan Jaringan Jalan', uraian: 'Pengembangan Jaringan Jalan' },
  { id: 215, kode: '600.1.16', deskripsi: 'Sistem Penyediaan Air Minum (SPAM)', uraian: 'Sistem Penyediaan Air Minum (SPAM)' },
  { id: 216, kode: '600.2', deskripsi: 'PERUMAHAN RAKYAT DAN KAWASAN PEMUKIMAN', uraian: 'PERUMAHAN RAKYAT DAN KAWASAN PEMUKIMAN' },
  { id: 217, kode: '600.2.10', deskripsi: 'Penyelenggaraan Jasa Konstruksi', uraian: 'Penyelenggaraan Jasa Konstruksi' },
  { id: 218, kode: '700', deskripsi: 'PENGAWASAN', uraian: 'PENGAWASAN' },
  { id: 219, kode: '700.1', deskripsi: 'PENGAWASAN INTERNAL', uraian: 'PENGAWASAN INTERNAL' },
  { id: 220, kode: '700.1.2', deskripsi: 'Pelaksanaan Pengawasan (Audit LHA/LHP/LHAI/Korupsi)', uraian: 'Pelaksanaan Pengawasan (Audit LHA/LHP/LHAI/Korupsi)' },
  { id: 221, kode: '800', deskripsi: 'KEPEGAWAIAN', uraian: 'KEPEGAWAIAN' },
  { id: 222, kode: '800.1', deskripsi: 'SUMBER DAYA MANUSIA', uraian: 'SUMBER DAYA MANUSIA' },
  { id: 223, kode: '800.1.2', deskripsi: 'Formasi dan Pengadaan Pegawai (CPNS/PPPK)', uraian: 'Formasi dan Pengadaan Pegawai (CPNS/PPPK)' },
  { id: 224, kode: '800.1.3', deskripsi: 'Mutasi Pegawai (Pindah Instansi/Kenaikan Pangkat)', uraian: 'Mutasi Pegawai (Pindah Instansi/Kenaikan Pangkat)' },
  { id: 225, kode: '800.1.4', deskripsi: 'Pengembangan Karir (Tugas Belajar/Ujian Dinas)', uraian: 'Pengembangan Karir (Tugas Belajar/Ujian Dinas)' },
  { id: 226, kode: '800.1.6', deskripsi: 'Kode Etik Disiplin dan Pensiun', uraian: 'Kode Etik Disiplin dan Pensiun' },
  { id: 227, kode: '800.1.11', deskripsi: 'Administrasi Pegawai (Cuti/Karpeg/DUK)', uraian: 'Administrasi Pegawai (Cuti/Karpeg/DUK)' },
  { id: 228, kode: '800.1.12', deskripsi: 'Kesejahteraan Pegawai (BPJS/Tali Kasih)', uraian: 'Kesejahteraan Pegawai (BPJS/Tali Kasih)' },
  { id: 229, kode: '900', deskripsi: 'KEUANGAN', uraian: 'KEUANGAN' },
  { id: 230, kode: '900.1', deskripsi: 'KEUANGAN DAERAH', uraian: 'KEUANGAN DAERAH' },
  { id: 231, kode: '900.1.1', deskripsi: 'Penyusunan RAPBD / APBD-P', uraian: 'Penyusunan RAPBD / APBD-P' },
  { id: 232, kode: '900.1.3', deskripsi: 'Pelaksanaan Anggaran (SPP/SPM/SP2D)', uraian: 'Pelaksanaan Anggaran (SPP/SPM/SP2D)' },
  { id: 233, kode: '900.1.13', deskripsi: 'Pendapatan dan Investasi Daerah (Pajak/Retribusi/BUMD)', uraian: 'Pendapatan dan Investasi Daerah (Pajak/Retribusi/BUMD)' },
  { id: 234, kode: '900.1.14', deskripsi: 'Fasilitasi Dana Perimbangan (DAU/DAK/DBH)', uraian: 'Fasilitasi Dana Perimbangan (DAU/DAK/DBH)' }
]

export const klasifikasiService = {
  async getKlasifikasi(retries = 1) {
    try {
      const response = await apiClient.get('/klasifikasi.php')
      const formattedData = response.data.map(item => ({
        id: item.id,
        kode: item.kode,
        deskripsi: item.uraian || item.deskripsi,
        uraian: item.uraian || item.deskripsi
      }))
      if (!formattedData || formattedData.length < 234) {
        return { data: mockKlasifikasi }
      }
      return { data: formattedData }
    } catch (error) {
      console.warn('Gagal terhubung ke database klasifikasi, menggunakan data klasifikasi cadangan (mock data).')
      return { data: mockKlasifikasi }
    }
  }
}
