import { useQuery } from '@tanstack/react-query';
import api from '@/lib/axios';

export interface KlasifikasiItem {
  id: number;
  kode: string;
  nama: string;
  uraian?: string;
  aktif: boolean;
}

export const FALLBACK_KLASIFIKASI_234: KlasifikasiItem[] = [
  { id: 1, kode: '000', nama: 'UMUM', uraian: 'UMUM', aktif: true },
  { id: 2, kode: '000.1', nama: 'KETATAUSAHAAN DAN KERUMAHTANGGAAN', uraian: 'KETATAUSAHAAN DAN KERUMAHTANGGAAN', aktif: true },
  { id: 3, kode: '000.1.1', nama: 'Telekomunikasi', uraian: 'Telekomunikasi', aktif: true },
  { id: 4, kode: '000.1.2', nama: 'Perjalanan Dinas Dalam Negeri', uraian: 'Perjalanan Dinas Dalam Negeri', aktif: true },
  { id: 5, kode: '000.1.2.1', nama: 'Perjalanan Dinas Kepala Daerah', uraian: 'Perjalanan Dinas Kepala Daerah', aktif: true },
  { id: 6, kode: '000.1.2.2', nama: 'Perjalanan Dinas DPRD', uraian: 'Perjalanan Dinas DPRD', aktif: true },
  { id: 7, kode: '000.1.2.3', nama: 'Perjalanan Dinas Pegawai', uraian: 'Perjalanan Dinas Pegawai', aktif: true },
  { id: 8, kode: '000.1.3', nama: 'Perjalanan Dinas Luar Negeri', uraian: 'Perjalanan Dinas Luar Negeri', aktif: true },
  { id: 9, kode: '000.1.3.1', nama: 'Perjalanan Dinas Kepala Daerah', uraian: 'Perjalanan Dinas Kepala Daerah', aktif: true },
  { id: 10, kode: '000.1.3.2', nama: 'Perjalanan Dinas DPRD', uraian: 'Perjalanan Dinas DPRD', aktif: true },
  { id: 11, kode: '000.1.3.3', nama: 'Perjalanan Dinas Pegawai', uraian: 'Perjalanan Dinas Pegawai', aktif: true },
  { id: 12, kode: '000.1.4', nama: 'Penggunaan Fasilitas Kantor (Ruang/Gedung/Kendaraan/Wisma)', uraian: 'Penggunaan Fasilitas Kantor (Ruang/Gedung/Kendaraan/Wisma)', aktif: true },
  { id: 13, kode: '000.1.5', nama: 'Rapat Pimpinan (Notula/Risalah)', uraian: 'Rapat Pimpinan (Notula/Risalah)', aktif: true },
  { id: 14, kode: '000.1.6', nama: 'Penyediaan Konsumsi', uraian: 'Penyediaan Konsumsi', aktif: true },
  { id: 15, kode: '000.1.7', nama: 'Pengurusan Kendaraan Dinas', uraian: 'Pengurusan Kendaraan Dinas', aktif: true },
  { id: 16, kode: '000.1.7.1', nama: 'Pengurusan surat-surat kendaraan dinas', uraian: 'Pengurusan surat-surat kendaraan dinas', aktif: true },
  { id: 17, kode: '000.1.7.2', nama: 'Pemeliharaan dan perbaikan', uraian: 'Pemeliharaan dan perbaikan', aktif: true },
  { id: 18, kode: '000.1.7.3', nama: 'Pengurusan kehilangan dan masalah kendaraan', uraian: 'Pengurusan kehilangan dan masalah kendaraan', aktif: true },
  { id: 19, kode: '000.1.8', nama: 'Pemeliharaan Gedung Taman dan Peralatan Kantor', uraian: 'Pemeliharaan Gedung Taman dan Peralatan Kantor', aktif: true },
  { id: 20, kode: '000.1.8.1', nama: 'Pertamanan/ Landscape', uraian: 'Pertamanan/ Landscape', aktif: true },
  { id: 21, kode: '000.1.8.2', nama: 'Penghijauan', uraian: 'Penghijauan', aktif: true },
  { id: 22, kode: '000.1.8.3', nama: 'Perbaikan Gedung', uraian: 'Perbaikan Gedung', aktif: true },
  { id: 23, kode: '000.1.8.4', nama: 'Perbaikan Peralatan Kantor', uraian: 'Perbaikan Peralatan Kantor', aktif: true },
  { id: 24, kode: '000.1.8.5', nama: 'Perbaikan Rumah Dinas/ Wisma', uraian: 'Perbaikan Rumah Dinas/ Wisma', aktif: true },
  { id: 25, kode: '000.1.8.6', nama: 'Kebersihan Gedung dan Taman', uraian: 'Kebersihan Gedung dan Taman', aktif: true },
  { id: 26, kode: '000.1.9', nama: 'Pengelolaan Jaringan Listrik Air Telepon dan Komputer', uraian: 'Pengelolaan Jaringan Listrik Air Telepon dan Komputer', aktif: true },
  { id: 27, kode: '000.1.9.1', nama: 'Perbaikan / Pemeliharaan', uraian: 'Perbaikan / Pemeliharaan', aktif: true },
  { id: 28, kode: '000.1.9.2', nama: 'Pemasangan', uraian: 'Pemasangan', aktif: true },
  { id: 29, kode: '000.1.10', nama: 'Ketertiban dan Keamanan', uraian: 'Ketertiban dan Keamanan', aktif: true },
  { id: 30, kode: '000.1.10.1', nama: 'Pengamanan Penjagaan dan Pengawalan Pejabat/Kantor/Rumah Dinas', uraian: 'Pengamanan Penjagaan dan Pengawalan Pejabat/Kantor/Rumah Dinas', aktif: true },
  { id: 31, kode: '000.1.10.2', nama: 'Laporan Ketertiban dan Keamanan', uraian: 'Laporan Ketertiban dan Keamanan', aktif: true },
  { id: 32, kode: '000.1.11', nama: 'Administrasi Pengelolaan Parkir', uraian: 'Administrasi Pengelolaan Parkir', aktif: true },
  { id: 33, kode: '000.1.12', nama: 'Administrasi Pakaian Dinas (Pegawai/Satpam/Kebersihan)', uraian: 'Administrasi Pakaian Dinas (Pegawai/Satpam/Kebersihan)', aktif: true },
  { id: 34, kode: '000.2', nama: 'PERLENGKAPAN', uraian: 'PERLENGKAPAN', aktif: true },
  { id: 35, kode: '000.2.1', nama: 'Inventarisasi dan Penyimpanan', uraian: 'Inventarisasi dan Penyimpanan', aktif: true },
  { id: 36, kode: '000.2.1.1', nama: 'Data hasil inventarisasi dan penyimpanan', uraian: 'Data hasil inventarisasi dan penyimpanan', aktif: true },
  { id: 37, kode: '000.2.2.2', nama: 'Laporan dan evaluasi inventarisasi dan penyimpanan', uraian: 'Laporan dan evaluasi inventarisasi dan penyimpanan', aktif: true },
  { id: 38, kode: '000.2.2', nama: 'Pemeliharaan peralatan kantor', uraian: 'Pemeliharaan peralatan kantor', aktif: true },
  { id: 39, kode: '000.2.2.1', nama: 'Data hasil pemeliharaan kantor', uraian: 'Data hasil pemeliharaan kantor', aktif: true },
  { id: 40, kode: '000.2.3', nama: 'Distribusi', uraian: 'Distribusi', aktif: true },
  { id: 41, kode: '000.2.3.1', nama: 'Barang habis pakai', uraian: 'Barang habis pakai', aktif: true },
  { id: 42, kode: '000.2.3.2', nama: 'Barang milik daerah', uraian: 'Barang milik daerah', aktif: true },
  { id: 43, kode: '000.2.4', nama: 'Penghapusan Barang Milik Daerah (SK Tim/Berita Acara/Lelang)', uraian: 'Penghapusan Barang Milik Daerah (SK Tim/Berita Acara/Lelang)', aktif: true },
  { id: 44, kode: '000.2.5', nama: 'Pengelolaan Database Barang Milik Daerah', uraian: 'Pengelolaan Database Barang Milik Daerah', aktif: true },
  { id: 45, kode: '000.3', nama: 'PENGADAAN', uraian: 'PENGADAAN', aktif: true },
  { id: 46, kode: '000.3.1', nama: 'Rencana pengadaan Barang dan jasa (Identifikasi/Penyusunan RKP/KAK/RUP)', uraian: 'Rencana pengadaan Barang dan jasa (Identifikasi/Penyusunan RKP/KAK/RUP)', aktif: true },
  { id: 47, kode: '000.3.2', nama: 'Pengadaan Langsung (Pemilihan/Kontrak/Pelaksanaan)', uraian: 'Pengadaan Langsung (Pemilihan/Kontrak/Pelaksanaan)', aktif: true },
  { id: 48, kode: '000.3.3', nama: 'Pengadaan Tidak Langsung/Lelang', uraian: 'Pengadaan Tidak Langsung/Lelang', aktif: true },
  { id: 49, kode: '000.3.4', nama: 'Swakelola (Perencanaan/Pelaksanaan/Evaluasi)', uraian: 'Swakelola (Perencanaan/Pelaksanaan/Evaluasi)', aktif: true },
  { id: 50, kode: '000.3.5', nama: 'Pengolahan Sistem Informasi Pengadaan (Database/Kontrak)', uraian: 'Pengolahan Sistem Informasi Pengadaan (Database/Kontrak)', aktif: true },
  { id: 51, kode: '000.3.6', nama: 'Monitoring dan evaluasi pelaksanaan pengadaan', uraian: 'Monitoring dan evaluasi pelaksanaan pengadaan', aktif: true },
  { id: 52, kode: '000.4', nama: 'PERPUSTAKAAN', uraian: 'PERPUSTAKAAN', aktif: true },
  { id: 53, kode: '000.4.1', nama: 'Kebijakan di bidang Perpustakaan', uraian: 'Kebijakan di bidang Perpustakaan', aktif: true },
  { id: 54, kode: '000.4.2', nama: 'Deposit Bahan Pustaka', uraian: 'Deposit Bahan Pustaka', aktif: true },
  { id: 55, kode: '000.4.2.1', nama: 'Serah Simpan Karya Cetak dan Karya Rekam', uraian: 'Serah Simpan Karya Cetak dan Karya Rekam', aktif: true },
  { id: 56, kode: '000.4.2.2', nama: 'Pangkalan Data Penerbit dan Pengusaha Rekaman', uraian: 'Pangkalan Data Penerbit dan Pengusaha Rekaman', aktif: true },
  { id: 57, kode: '000.4.2.3', nama: 'Terbitan Internasional dan Regional', uraian: 'Terbitan Internasional dan Regional', aktif: true },
  { id: 58, kode: '000.4.2.4', nama: 'Pemantauan Wajib Serah Simpan', uraian: 'Pemantauan Wajib Serah Simpan', aktif: true },
  { id: 59, kode: '000.4.2.5', nama: 'Bibliografi dan Katalog', uraian: 'Bibliografi dan Katalog', aktif: true },
  { id: 60, kode: '000.4.3', nama: 'Koleksi Pustaka (Pembelian/Hibah/Hadiah/Tukar Menukar)', uraian: 'Koleksi Pustaka (Pembelian/Hibah/Hadiah/Tukar Menukar)', aktif: true },
  { id: 61, kode: '000.4.4', nama: 'Pengolahan Bahan Pustaka', uraian: 'Pengolahan Bahan Pustaka', aktif: true },
  { id: 62, kode: '000.4.5', nama: 'Pangkalan Data Katalog Koleksi', uraian: 'Pangkalan Data Katalog Koleksi', aktif: true },
  { id: 63, kode: '000.4.6', nama: 'Layanan Perpustakaan (Keanggotaan/Peminjaman/Gemar Baca)', uraian: 'Layanan Perpustakaan (Keanggotaan/Peminjaman/Gemar Baca)', aktif: true },
  { id: 64, kode: '000.4.7', nama: 'Kerjasama Perpustakaan (MoU/Perjanjian)', uraian: 'Kerjasama Perpustakaan (MoU/Perjanjian)', aktif: true },
  { id: 65, kode: '000.4.8', nama: 'Pengembangan Implementasi Teknologi Informasi Perpustakaan', uraian: 'Pengembangan Implementasi Teknologi Informasi Perpustakaan', aktif: true },
  { id: 66, kode: '000.4.10', nama: 'Konservasi (Perawatan/Perbaikan/Penjilidan)', uraian: 'Konservasi (Perawatan/Perbaikan/Penjilidan)', aktif: true },
  { id: 67, kode: '000.5', nama: 'KEARSIPAN', uraian: 'KEARSIPAN', aktif: true },
  { id: 68, kode: '000.5.1', nama: 'Kebijakan di bidang kearsipan oleh Pemerintah Daerah', uraian: 'Kebijakan di bidang kearsipan oleh Pemerintah Daerah', aktif: true },
  { id: 69, kode: '000.5.2', nama: 'Pembinaan Kearsipan', uraian: 'Pembinaan Kearsipan', aktif: true },
  { id: 70, kode: '000.5.2.1', nama: 'Pengembangan Profesi Arsiparis (Formasi/Analisis Kebutuhan)', uraian: 'Pengembangan Profesi Arsiparis (Formasi/Analisis Kebutuhan)', aktif: true },
  { id: 71, kode: '000.5.2.2', nama: 'Bimbingan Konsultasi Arsiparis', uraian: 'Bimbingan Konsultasi Arsiparis', aktif: true },
  { id: 72, kode: '000.5.2.3', nama: 'Penilaian Arsiparis', uraian: 'Penilaian Arsiparis', aktif: true },
  { id: 73, kode: '000.5.2.4', nama: 'Pemilihan Arsiparis Teladan', uraian: 'Pemilihan Arsiparis Teladan', aktif: true },
  { id: 74, kode: '000.5.2.5', nama: 'Data Base Arsiparis', uraian: 'Data Base Arsiparis', aktif: true },
  { id: 75, kode: '000.5.2.7', nama: 'Supervisi dan Evaluasi Kearsipan', uraian: 'Supervisi dan Evaluasi Kearsipan', aktif: true },
  { id: 76, kode: '000.5.3', nama: 'Pengelolaan Arsip Dinamis', uraian: 'Pengelolaan Arsip Dinamis', aktif: true },
  { id: 77, kode: '000.5.3.1', nama: 'Penciptaan (Registrasi/Buku Agenda/Kartu Kendali)', uraian: 'Penciptaan (Registrasi/Buku Agenda/Kartu Kendali)', aktif: true },
  { id: 78, kode: '000.5.3.2', nama: 'Pemberkasan Arsip Aktif', uraian: 'Pemberkasan Arsip Aktif', aktif: true },
  { id: 79, kode: '000.5.3.3', nama: 'Penataan Arsip Inaktif', uraian: 'Penataan Arsip Inaktif', aktif: true },
  { id: 80, kode: '000.5.3.4', nama: 'Penggunaan dan Bukti Peminjaman Arsip', uraian: 'Penggunaan dan Bukti Peminjaman Arsip', aktif: true },
  { id: 81, kode: '000.5.3.5', nama: 'Autentikasi Arsip Dinamis', uraian: 'Autentikasi Arsip Dinamis', aktif: true },
  { id: 82, kode: '000.5.4', nama: 'Program Arsip Vital (Identifikasi/Perlindungan/Penyelamatan)', uraian: 'Program Arsip Vital (Identifikasi/Perlindungan/Penyelamatan)', aktif: true },
  { id: 83, kode: '000.5.5', nama: 'Pengelolaan Arsip Terjaga', uraian: 'Pengelolaan Arsip Terjaga', aktif: true },
  { id: 84, kode: '000.5.6', nama: 'Penyusutan Arsip', uraian: 'Penyusutan Arsip', aktif: true },
  { id: 85, kode: '000.5.6.1', nama: 'Pemindahan Arsip', uraian: 'Pemindahan Arsip', aktif: true },
  { id: 86, kode: '000.5.6.2', nama: 'Pemusnahan Arsip (SK Panitia/Persetujuan ANRI/Berita Acara)', uraian: 'Pemusnahan Arsip (SK Panitia/Persetujuan ANRI/Berita Acara)', aktif: true },
  { id: 87, kode: '000.5.6.3', nama: 'Penyerahan Arsip Statis', uraian: 'Penyerahan Arsip Statis', aktif: true },
  { id: 88, kode: '000.5.7', nama: 'Alih Media Arsip (Digitalisasi)', uraian: 'Alih Media Arsip (Digitalisasi)', aktif: true },
  { id: 89, kode: '000.5.9', nama: 'Pengelolaan Arsip Statis', uraian: 'Pengelolaan Arsip Statis', aktif: true },
  { id: 90, kode: '000.5.9.1', nama: 'Akuisisi Arsip Statis', uraian: 'Akuisisi Arsip Statis', aktif: true },
  { id: 91, kode: '000.5.9.3', nama: 'Sejarah Lisan (Wawancara/Hasil Rekaman)', uraian: 'Sejarah Lisan (Wawancara/Hasil Rekaman)', aktif: true },
  { id: 92, kode: '000.5.9.5', nama: 'Penyusunan Sarana Bantu Temu Balik (Inventory/Guide)', uraian: 'Penyusunan Sarana Bantu Temu Balik (Inventory/Guide)', aktif: true },
  { id: 93, kode: '000.5.9.6', nama: 'Preservasi Preventif (Penyimpanan/Hama)', uraian: 'Preservasi Preventif (Penyimpanan/Hama)', aktif: true },
  { id: 94, kode: '000.5.15', nama: 'Pengawasan Kearsipan (Internal/Eksternal)', uraian: 'Pengawasan Kearsipan (Internal/Eksternal)', aktif: true },
  { id: 95, kode: '000.6', nama: 'PERSANDIAN', uraian: 'PERSANDIAN', aktif: true },
  { id: 96, kode: '000.6.1', nama: 'Kebijakan di bidang Persandian', uraian: 'Kebijakan di bidang Persandian', aktif: true },
  { id: 97, kode: '000.6.2', nama: 'Pengamanan Persandian (Sinyal/Kripto/Materiil)', uraian: 'Pengamanan Persandian (Sinyal/Kripto/Materiil)', aktif: true },
  { id: 98, kode: '000.6.3', nama: 'Pengkajian Persandian (Kriptografi/Komunikasi Sandi)', uraian: 'Pengkajian Persandian (Kriptografi/Komunikasi Sandi)', aktif: true },
  { id: 99, kode: '000.6.5', nama: 'Layanan Sertifikasi Elektronik', uraian: 'Layanan Sertifikasi Elektronik', aktif: true },
  { id: 100, kode: '000.7', nama: 'PERENCANAAN PEMBANGUNAN', uraian: 'PERENCANAAN PEMBANGUNAN', aktif: true },
  { id: 101, kode: '000.7.1', nama: 'Musrenbang (Provinsi/Nasional/Kota/Kecamatan/Desa)', uraian: 'Musrenbang (Provinsi/Nasional/Kota/Kecamatan/Desa)', aktif: true },
  { id: 102, kode: '000.7.2', nama: 'Perencanaan Pembangunan Daerah', uraian: 'Perencanaan Pembangunan Daerah', aktif: true },
  { id: 103, kode: '000.7.2.1', nama: 'Rencana Pembangunan Jangka Panjang (RPJP)', uraian: 'Rencana Pembangunan Jangka Panjang (RPJP)', aktif: true },
  { id: 104, kode: '000.7.2.2', nama: 'Rencana Pembangunan Jangka Menengah (RPJM)', uraian: 'Rencana Pembangunan Jangka Menengah (RPJM)', aktif: true },
  { id: 105, kode: '000.7.2.4', nama: 'Rencana Pembangunan Tahunan (RKP)', uraian: 'Rencana Pembangunan Tahunan (RKP)', aktif: true },
  { id: 106, kode: '000.7.2.7', nama: 'Penetapan / Kontrak Kinerja', uraian: 'Penetapan / Kontrak Kinerja', aktif: true },
  { id: 107, kode: '000.8', nama: 'ORGANISASI DAN TATA LAKSANA', uraian: 'ORGANISASI DAN TATA LAKSANA', aktif: true },
  { id: 108, kode: '000.8.1', nama: 'Struktur Organisasi (Pembentukan/Pengubahan/Pembubaran)', uraian: 'Struktur Organisasi (Pembentukan/Pengubahan/Pembubaran)', aktif: true },
  { id: 109, kode: '000.8.2', nama: 'Uraian Jabatan (Analisa Jabatan/Beban Kerja)', uraian: 'Uraian Jabatan (Analisa Jabatan/Beban Kerja)', aktif: true },
  { id: 110, kode: '000.8.3', nama: 'Ketatalaksanaan (Proses Bisnis/SOP/Pelayanan Publik)', uraian: 'Ketatalaksanaan (Proses Bisnis/SOP/Pelayanan Publik)', aktif: true },
  { id: 111, kode: '000.8.6', nama: 'Koordinasi Penguatan Reformasi dan Birokrasi', uraian: 'Koordinasi Penguatan Reformasi dan Birokrasi', aktif: true },
  { id: 112, kode: '000.9', nama: 'PENELITIAN PENGKAJIAN DAN PENGEMBANGAN', uraian: 'PENELITIAN PENGKAJIAN DAN PENGEMBANGAN', aktif: true },
  { id: 113, kode: '100', nama: 'PEMERINTAHAN', uraian: 'PEMERINTAHAN', aktif: true },
  { id: 114, kode: '100.1', nama: 'OTONOMI DAERAH', uraian: 'OTONOMI DAERAH', aktif: true },
  { id: 115, kode: '100.1.2', nama: 'Penyelenggaraan Pemerintah Daerah (Fasilitasi/Monitoring)', uraian: 'Penyelenggaraan Pemerintah Daerah (Fasilitasi/Monitoring)', aktif: true },
  { id: 116, kode: '100.1.3', nama: 'Penataan Daerah (Pemekaran/Otsus)', uraian: 'Penataan Daerah (Pemekaran/Otsus)', aktif: true },
  { id: 117, kode: '100.1.4', nama: 'Pemilihan Kepala Daerah dan DPRD', uraian: 'Pemilihan Kepala Daerah dan DPRD', aktif: true },
  { id: 118, kode: '100.2', nama: 'PEMERINTAHAN UMUM', uraian: 'PEMERINTAHAN UMUM', aktif: true },
  { id: 119, kode: '100.2.1', nama: 'Kebijakan bidang Pemerintahan Umum', uraian: 'Kebijakan bidang Pemerintahan Umum', aktif: true },
  { id: 120, kode: '100.2.2', nama: 'Dekonsentrasi dan Kerjasama', uraian: 'Dekonsentrasi dan Kerjasama', aktif: true },
  { id: 121, kode: '100.2.3', nama: 'Wilayah Administrasi dan Perbatasan (Toponimi/Batas Daerah)', uraian: 'Wilayah Administrasi dan Perbatasan (Toponimi/Batas Daerah)', aktif: true },
  { id: 122, kode: '100.3', nama: 'HUKUM', uraian: 'HUKUM', aktif: true },
  { id: 123, kode: '100.3.1', nama: 'Program Legislasi', uraian: 'Program Legislasi', aktif: true },
  { id: 124, kode: '100.3.2', nama: 'Rancangan Peraturan Perundang-Undangan (Perda/Naskah Akademik)', uraian: 'Rancangan Peraturan Perundang-Undangan (Perda/Naskah Akademik)', aktif: true },
  { id: 125, kode: '100.3.3', nama: 'Keputusan/Ketetapan Pimpinan (Gubernur/Bupati/Walikota/Sekda)', uraian: 'Keputusan/Ketetapan Pimpinan (Gubernur/Bupati/Walikota/Sekda)', aktif: true },
  { id: 126, kode: '100.3.4', nama: 'Instruksi / Surat Edaran', uraian: 'Instruksi / Surat Edaran', aktif: true },
  { id: 127, kode: '100.3.5', nama: 'Surat Perintah', uraian: 'Surat Perintah', aktif: true },
  { id: 128, kode: '100.3.7', nama: 'Nota Kesepakatan (MOU) / Kontrak / Perjanjian', uraian: 'Nota Kesepakatan (MOU) / Kontrak / Perjanjian', aktif: true },
  { id: 129, kode: '100.3.11', nama: 'Kasus/ Sengketa Hukum (Pidana/Perdata/Arbitrase)', uraian: 'Kasus/ Sengketa Hukum (Pidana/Perdata/Arbitrase)', aktif: true },
  { id: 130, kode: '100.3.13', nama: 'Hak atas Kekayaan Intelektual (HAKI)', uraian: 'Hak atas Kekayaan Intelektual (HAKI)', aktif: true },
  { id: 131, kode: '200', nama: 'POLITIK', uraian: 'POLITIK', aktif: true },
  { id: 132, kode: '200.1', nama: 'KESATUAN BANGSA DAN POLITIK', uraian: 'KESATUAN BANGSA DAN POLITIK', aktif: true },
  { id: 133, kode: '200.1.2', nama: 'Bina Ideologi dan Wawasan Kebangsaan (Bela Negara)', uraian: 'Bina Ideologi dan Wawasan Kebangsaan (Bela Negara)', aktif: true },
  { id: 134, kode: '200.1.3', nama: 'Kewaspadaan Nasional (Intelijen/Konflik Sosial)', uraian: 'Kewaspadaan Nasional (Intelijen/Konflik Sosial)', aktif: true },
  { id: 135, kode: '200.1.4', nama: 'Ketahanan Seni Budaya Adat Agama dan Kemasyarakatan (Ormas)', uraian: 'Ketahanan Seni Budaya Adat Agama dan Kemasyarakatan (Ormas)', aktif: true },
  { id: 136, kode: '200.1.5', nama: 'Politik Dalam Negeri (Parpol/Pemilu)', uraian: 'Politik Dalam Negeri (Parpol/Pemilu)', aktif: true },
  { id: 137, kode: '200.2', nama: 'PEMILU', uraian: 'PEMILU', aktif: true },
  { id: 138, kode: '200.2.2', nama: 'Pemutakhiran Daftar Pemilih (DP4/DPS/DPT)', uraian: 'Pemutakhiran Daftar Pemilih (DP4/DPS/DPT)', aktif: true },
  { id: 139, kode: '200.2.3', nama: 'Pendaftaran dan Verifikasi Peserta Pemilu', uraian: 'Pendaftaran dan Verifikasi Peserta Pemilu', aktif: true },
  { id: 140, kode: '200.2.8', nama: 'Pemungutan dan Penghitungan Suara', uraian: 'Pemungutan dan Penghitungan Suara', aktif: true },
  { id: 141, kode: '300', nama: 'KEAMANAN DAN KETERTIBAN', uraian: 'KEAMANAN DAN KETERTIBAN', aktif: true },
  { id: 142, kode: '300.1', nama: 'SATUAN POLISI PAMONG PRAJA (Satpol PP)', uraian: 'SATUAN POLISI PAMONG PRAJA (Satpol PP)', aktif: true },
  { id: 143, kode: '300.1.2', nama: 'Tata Operasional dan Sarana Prasarana Satpol PP', uraian: 'Tata Operasional dan Sarana Prasarana Satpol PP', aktif: true },
  { id: 144, kode: '300.2', nama: 'PENANGGULANGAN BENCANA PENCARIAN DAN PERTOLONGAN', uraian: 'PENANGGULANGAN BENCANA PENCARIAN DAN PERTOLONGAN', aktif: true },
  { id: 145, kode: '300.2.2', nama: 'Perencanaan Penanggulangan Bencana (SAR/Logistik)', uraian: 'Perencanaan Penanggulangan Bencana (SAR/Logistik)', aktif: true },
  { id: 146, kode: '300.2.8', nama: 'Operasi Komunikasi (Berita SAR/Beacon)', uraian: 'Operasi Komunikasi (Berita SAR/Beacon)', aktif: true },
  { id: 147, kode: '400', nama: 'KESEJAHTERAAN RAKYAT', uraian: 'KESEJAHTERAAN RAKYAT', aktif: true },
  { id: 148, kode: '400.1', nama: 'PEMBANGUNAN DAERAH TERTINGGAL', uraian: 'PEMBANGUNAN DAERAH TERTINGGAL', aktif: true },
  { id: 149, kode: '400.2', nama: 'PEMBERDAYAAN PEREMPUAN DAN PERLINDUNGAN ANAK', uraian: 'PEMBERDAYAAN PEREMPUAN DAN PERLINDUNGAN ANAK', aktif: true },
  { id: 150, kode: '400.2.3', nama: 'Perlindungan Perempuan (Kekerasan/Trafficking)', uraian: 'Perlindungan Perempuan (Kekerasan/Trafficking)', aktif: true },
  { id: 151, kode: '400.2.4', nama: 'Perlindungan Anak (Hak Sipil/Anak Berhadapan Hukum)', uraian: 'Perlindungan Anak (Hak Sipil/Anak Berhadapan Hukum)', aktif: true },
  { id: 152, kode: '400.2.5', nama: 'Tumbuh Kembang Anak (Kota Layak Anak)', uraian: 'Tumbuh Kembang Anak (Kota Layak Anak)', aktif: true },
  { id: 153, kode: '400.3', nama: 'PENDIDIKAN', uraian: 'PENDIDIKAN', aktif: true },
  { id: 154, kode: '400.3.2', nama: 'PAUD (Bahan Ajar/Alat Permainan Edukatif)', uraian: 'PAUD (Bahan Ajar/Alat Permainan Edukatif)', aktif: true },
  { id: 155, kode: '400.3.5', nama: 'Pendidikan Dasar dan Menengah Pertama (Kurikulum/BOS/Bantuan Siswa)', uraian: 'Pendidikan Dasar dan Menengah Pertama (Kurikulum/BOS/Bantuan Siswa)', aktif: true },
  { id: 156, kode: '400.3.7', nama: 'Pembinaan Pendidik dan Tenaga Pendidik (Sertifikasi Guru/UKG)', uraian: 'Pembinaan Pendidik dan Tenaga Pendidik (Sertifikasi Guru/UKG)', aktif: true },
  { id: 157, kode: '400.3.8', nama: 'Sekolah Menengah Atas', uraian: 'Sekolah Menengah Atas', aktif: true },
  { id: 158, kode: '400.3.10', nama: 'Pendidik dan Tenaga Pendidik (SKP/Penilaian Prestasi)', uraian: 'Pendidik dan Tenaga Pendidik (SKP/Penilaian Prestasi)', aktif: true },
  { id: 159, kode: '400.3.12', nama: 'Data dan Statistik Pendidikan', uraian: 'Data dan Statistik Pendidikan', aktif: true },
  { id: 160, kode: '400.4', nama: 'KEOLAHRAGAAN', uraian: 'KEOLAHRAGAAN', aktif: true },
  { id: 161, kode: '400.4.2', nama: 'Olahraga Pendidikan', uraian: 'Olahraga Pendidikan', aktif: true },
  { id: 162, kode: '400.4.3', nama: 'Olahraga Rekreasi (Massal/Tradisional)', uraian: 'Olahraga Rekreasi (Massal/Tradisional)', aktif: true },
  { id: 163, kode: '400.5', nama: 'KEPEMUDAAN', uraian: 'KEPEMUDAAN', aktif: true },
  { id: 164, kode: '400.5.2', nama: 'Peningkatan Tenaga dan Sumber Daya Pemuda (Duta Pemuda)', uraian: 'Peningkatan Tenaga dan Sumber Daya Pemuda (Duta Pemuda)', aktif: true },
  { id: 165, kode: '400.5.6', nama: 'Kepemimpinan dan Kepeloporan Pemuda', uraian: 'Kepemimpinan dan Kepeloporan Pemuda', aktif: true },
  { id: 166, kode: '400.6', nama: 'KEBUDAYAAN', uraian: 'KEBUDAYAAN', aktif: true },
  { id: 167, kode: '400.6.2', nama: 'Pelestarian Cagar Budaya dan Permuseuman', uraian: 'Pelestarian Cagar Budaya dan Permuseuman', aktif: true },
  { id: 168, kode: '400.6.3', nama: 'Pembinaan Kesenian dan Perfilman', uraian: 'Pembinaan Kesenian dan Perfilman', aktif: true },
  { id: 169, kode: '400.7', nama: 'KESEHATAN', uraian: 'KESEHATAN', aktif: true },
  { id: 170, kode: '400.7.2', nama: 'Upaya Kesehatan Dasar (Puskesmas/Kedokteran Keluarga)', uraian: 'Upaya Kesehatan Dasar (Puskesmas/Kedokteran Keluarga)', aktif: true },
  { id: 171, kode: '400.7.3', nama: 'Upaya Kesehatan Rujukan (Rumah Sakit/KUK)', uraian: 'Upaya Kesehatan Rujukan (Rumah Sakit/KUK)', aktif: true },
  { id: 172, kode: '400.7.8', nama: 'Pengendalian Penyakit Menular (TB/AIDS/ISPA)', uraian: 'Pengendalian Penyakit Menular (TB/AIDS/ISPA)', aktif: true },
  { id: 173, kode: '400.7.10', nama: 'Pengendalian Penyakit Tidak Menular (Jantung/Diabetes/Kanker)', uraian: 'Pengendalian Penyakit Tidak Menular (Jantung/Diabetes/Kanker)', aktif: true },
  { id: 174, kode: '400.7.13', nama: 'Gizi (Kewaspadaan Gizi/Stunting)', uraian: 'Gizi (Kewaspadaan Gizi/Stunting)', aktif: true },
  { id: 175, kode: '400.7.20', nama: 'Kefarmasian (Apotek/Obat Rasional)', uraian: 'Kefarmasian (Apotek/Obat Rasional)', aktif: true },
  { id: 176, kode: '400.9', nama: 'SOSIAL', uraian: 'SOSIAL', aktif: true },
  { id: 177, kode: '400.9.2', nama: 'Kesejahteraan Sosial Anak', uraian: 'Kesejahteraan Sosial Anak', aktif: true },
  { id: 178, kode: '400.9.4', nama: 'Rehabilitasi Sosial (Disabilitas/Tuna Sosial)', uraian: 'Rehabilitasi Sosial (Disabilitas/Tuna Sosial)', aktif: true },
  { id: 179, kode: '400.12', nama: 'KEPENDUDUKAN DAN CATATAN SIPIL', uraian: 'KEPENDUDUKAN DAN CATATAN SIPIL', aktif: true },
  { id: 180, kode: '400.12.3', nama: 'Pencatatan Sipil (Kelahiran/Kematian/Nikah/Cerai)', uraian: 'Pencatatan Sipil (Kelahiran/Kematian/Nikah/Cerai)', aktif: true },
  { id: 181, kode: '400.12.4', nama: 'Sistem Informasi Administrasi Kependudukan (SIAK)', uraian: 'Sistem Informasi Administrasi Kependudukan (SIAK)', aktif: true },
  { id: 182, kode: '400.13', nama: 'KELUARGA BERENCANA', uraian: 'KELUARGA BERENCANA', aktif: true },
  { id: 183, kode: '400.13.16', nama: 'Kualitas Pelayanan KB Pemerintah', uraian: 'Kualitas Pelayanan KB Pemerintah', aktif: true },
  { id: 184, kode: '400.13.26', nama: 'Bina Keluarga Balita dan Anak', uraian: 'Bina Keluarga Balita dan Anak', aktif: true },
  { id: 185, kode: '500', nama: 'PEREKONOMIAN', uraian: 'PEREKONOMIAN', aktif: true },
  { id: 186, kode: '500.1', nama: 'KETAHANAN PANGAN', uraian: 'KETAHANAN PANGAN', aktif: true },
  { id: 187, kode: '500.1.2', nama: 'Ketersediaan dan Kerawanan Pangan', uraian: 'Ketersediaan dan Kerawanan Pangan', aktif: true },
  { id: 188, kode: '500.2', nama: 'PERDAGANGAN', uraian: 'PERDAGANGAN', aktif: true },
  { id: 189, kode: '500.2.2', nama: 'Perdagangan Dalam Negeri (Pasar/UMKM)', uraian: 'Perdagangan Dalam Negeri (Pasar/UMKM)', aktif: true },
  { id: 190, kode: '500.3', nama: 'KOPERASI DAN USAHA KECIL MENENGAH', uraian: 'KOPERASI DAN USAHA KECIL MENENGAH', aktif: true },
  { id: 191, kode: '500.3.4', nama: 'Pembiayaan (Simpan Pinjam/Kredit)', uraian: 'Pembiayaan (Simpan Pinjam/Kredit)', aktif: true },
  { id: 192, kode: '500.4', nama: 'KEHUTANAN', uraian: 'KEHUTANAN', aktif: true },
  { id: 193, kode: '500.4.3', nama: 'Planologi Kehutanan (Tata Ruang Hutan)', uraian: 'Planologi Kehutanan (Tata Ruang Hutan)', aktif: true },
  { id: 194, kode: '500.4.6', nama: 'Perlindungan Hutan dan Konservasi Alam', uraian: 'Perlindungan Hutan dan Konservasi Alam', aktif: true },
  { id: 195, kode: '500.5', nama: 'KELAUTAN DAN PERIKANAN', uraian: 'KELAUTAN DAN PERIKANAN', aktif: true },
  { id: 196, kode: '500.5.2', nama: 'Perikanan Tangkap (Kapal/Alat Tangkap)', uraian: 'Perikanan Tangkap (Kapal/Alat Tangkap)', aktif: true },
  { id: 197, kode: '500.5.3', nama: 'Perikanan Budidaya (Benih/Hama Penyakit)', uraian: 'Perikanan Budidaya (Benih/Hama Penyakit)', aktif: true },
  { id: 198, kode: '500.6', nama: 'PERTANIAN', uraian: 'PERTANIAN', aktif: true },
  { id: 199, kode: '500.6.2', nama: 'Perlindungan Hortikultura', uraian: 'Perlindungan Hortikultura', aktif: true },
  { id: 200, kode: '500.6.10', nama: 'Budidaya Serealia (Padi/Jagung)', uraian: 'Budidaya Serealia (Padi/Jagung)', aktif: true },
  { id: 201, kode: '500.9', nama: 'PERINDUSTRIAN', uraian: 'PERINDUSTRIAN', aktif: true },
  { id: 202, kode: '500.10', nama: 'ENERGI DAN SUMBER DAYA MINERAL', uraian: 'ENERGI DAN SUMBER DAYA MINERAL', aktif: true },
  { id: 203, kode: '500.10.7', nama: 'Hulu Minyak dan Gas Bumi (Eksplorasi/Eksploitasi)', uraian: 'Hulu Minyak dan Gas Bumi (Eksplorasi/Eksploitasi)', aktif: true },
  { id: 204, kode: '500.10.12', nama: 'Panas Bumi', uraian: 'Panas Bumi', aktif: true },
  { id: 205, kode: '500.11', nama: 'PERHUBUNGAN', uraian: 'PERHUBUNGAN', aktif: true },
  { id: 206, kode: '500.11.2', nama: 'Jaringan Prasarana (Terminal Tipe A/B/C)', uraian: 'Jaringan Prasarana (Terminal Tipe A/B/C)', aktif: true },
  { id: 207, kode: '500.11.8', nama: 'Angkutan Penumpang (Tarif/Izin Trayek)', uraian: 'Angkutan Penumpang (Tarif/Izin Trayek)', aktif: true },
  { id: 208, kode: '500.12', nama: 'KOMUNIKASI DAN INFORMATIKA', uraian: 'KOMUNIKASI DAN INFORMATIKA', aktif: true },
  { id: 209, kode: '500.12.6', nama: 'e-Government (Tata Kelola/Aplikasi)', uraian: 'e-Government (Tata Kelola/Aplikasi)', aktif: true },
  { id: 210, kode: '600', nama: 'PEKERJAAN UMUM DAN KETENAGAAN', uraian: 'PEKERJAAN UMUM DAN KETENAGAAN', aktif: true },
  { id: 211, kode: '600.1', nama: 'PEKERJAAN UMUM', uraian: 'PEKERJAAN UMUM', aktif: true },
  { id: 212, kode: '600.1.2', nama: 'Penatagunaan Sumber Daya Air', uraian: 'Penatagunaan Sumber Daya Air', aktif: true },
  { id: 213, kode: '600.1.7', nama: 'Pengembangan Jaringan Jalan', uraian: 'Pengembangan Jaringan Jalan', aktif: true },
  { id: 214, kode: '600.1.16', nama: 'Sistem Penyediaan Air Minum (SPAM)', uraian: 'Sistem Penyediaan Air Minum (SPAM)', aktif: true },
  { id: 215, kode: '600.2', nama: 'PERUMAHAN RAKYAT DAN KAWASAN PEMUKIMAN', uraian: 'PERUMAHAN RAKYAT DAN KAWASAN PEMUKIMAN', aktif: true },
  { id: 216, kode: '600.2.10', nama: 'Penyelenggaraan Jasa Konstruksi', uraian: 'Penyelenggaraan Jasa Konstruksi', aktif: true },
  { id: 217, kode: '700', nama: 'PENGAWASAN', uraian: 'PENGAWASAN', aktif: true },
  { id: 218, kode: '700.1', nama: 'PENGAWASAN INTERNAL', uraian: 'PENGAWASAN INTERNAL', aktif: true },
  { id: 219, kode: '700.1.2', nama: 'Pelaksanaan Pengawasan (Audit LHA/LHP/LHAI/Korupsi)', uraian: 'Pelaksanaan Pengawasan (Audit LHA/LHP/LHAI/Korupsi)', aktif: true },
  { id: 220, kode: '800', nama: 'KEPEGAWAIAN', uraian: 'KEPEGAWAIAN', aktif: true },
  { id: 221, kode: '800.1', nama: 'SUMBER DAYA MANUSIA', uraian: 'SUMBER DAYA MANUSIA', aktif: true },
  { id: 222, kode: '800.1.2', nama: 'Formasi dan Pengadaan Pegawai (CPNS/PPPK)', uraian: 'Formasi dan Pengadaan Pegawai (CPNS/PPPK)', aktif: true },
  { id: 223, kode: '800.1.3', nama: 'Mutasi Pegawai (Pindah Instansi/Kenaikan Pangkat)', uraian: 'Mutasi Pegawai (Pindah Instansi/Kenaikan Pangkat)', aktif: true },
  { id: 224, kode: '800.1.4', nama: 'Pengembangan Karir (Tugas Belajar/Ujian Dinas)', uraian: 'Pengembangan Karir (Tugas Belajar/Ujian Dinas)', aktif: true },
  { id: 225, kode: '800.1.6', nama: 'Kode Etik Disiplin dan Pensiun', uraian: 'Kode Etik Disiplin dan Pensiun', aktif: true },
  { id: 226, kode: '800.1.11', nama: 'Administrasi Pegawai (Cuti/Karpeg/DUK)', uraian: 'Administrasi Pegawai (Cuti/Karpeg/DUK)', aktif: true },
  { id: 227, kode: '800.1.12', nama: 'Kesejahteraan Pegawai (BPJS/Tali Kasih)', uraian: 'Kesejahteraan Pegawai (BPJS/Tali Kasih)', aktif: true },
  { id: 228, kode: '900', nama: 'KEUANGAN', uraian: 'KEUANGAN', aktif: true },
  { id: 229, kode: '900.1', nama: 'KEUANGAN DAERAH', uraian: 'KEUANGAN DAERAH', aktif: true },
  { id: 230, kode: '900.1.1', nama: 'Penyusunan RAPBD / APBD-P', uraian: 'Penyusunan RAPBD / APBD-P', aktif: true },
  { id: 231, kode: '900.1.3', nama: 'Pelaksanaan Anggaran (SPP/SPM/SP2D)', uraian: 'Pelaksanaan Anggaran (SPP/SPM/SP2D)', aktif: true },
  { id: 232, kode: '900.1.13', nama: 'Pendapatan dan Investasi Daerah (Pajak/Retribusi/BUMD)', uraian: 'Pendapatan dan Investasi Daerah (Pajak/Retribusi/BUMD)', aktif: true },
  { id: 233, kode: '900.1.14', nama: 'Fasilitasi Dana Perimbangan (DAU/DAK/DBH)', uraian: 'Fasilitasi Dana Perimbangan (DAU/DAK/DBH)', aktif: true },
];

export const useKlasifikasi = (search?: string) => {
  return useQuery({
    queryKey: ['klasifikasi', search],
    queryFn: async () => {
      try {
        const params: Record<string, string> = {};
        if (search) params.search = search;
        const response = await api.get<KlasifikasiItem[]>('/klasifikasi', { params });
        if (!response.data || response.data.length < 234) {
          if (search) {
            const q = search.toLowerCase();
            return FALLBACK_KLASIFIKASI_234.filter(
              (item) => item.kode.toLowerCase().includes(q) || item.nama.toLowerCase().includes(q)
            );
          }
          return FALLBACK_KLASIFIKASI_234;
        }
        return response.data;
      } catch (err) {
        if (search) {
          const q = search.toLowerCase();
          return FALLBACK_KLASIFIKASI_234.filter(
            (item) => item.kode.toLowerCase().includes(q) || item.nama.toLowerCase().includes(q)
          );
        }
        return FALLBACK_KLASIFIKASI_234;
      }
    },
  });
};
